//auth
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const LOG_OUT = 'LOG_OUT';

//navbar
export const SET_NAVBAR_VISIBILITY = 'SET_NAVBAR_VISIBILITY';

//profile
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const SET_PROFILES_BY_SEARCH = 'SET_PROFILES_BY_SEARCH';

//posts
export const SET_POSTS = 'SET_POSTS';
export const SORT_POSTS_BY_TIME = 'SORT_POSTS_BY_TIME';
export const UPDATE_IS_POST_UPLOADED = 'UPDATE_IS_POST_UPLOADED';
export const SET_COMMENTS = 'SET_COMMENTS';
export const UPDATE_POSTS_IS_LOADED = 'UPDATE_POSTS_IS_LOADED';
export const UPDATE_COMMENTS_IS_LOADED = 'UPDATE_COMMENTS_IS_LOADED';
export const ADD_NEW_POST_WITH_INDEX = 'ADD_NEW_POST_WITH_INDEX';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
